// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxrPNYTt9RJN6it4E5ldrI5_hRubDGeh8',
    appId: '1:862488719088:web:fe9145eda80cce87449c35',
    messagingSenderId: '862488719088',
    projectId: 'genuine-app-20b4a',
    authDomain: 'genuine-app-20b4a.firebaseapp.com',
    storageBucket: 'genuine-app-20b4a.appspot.com',
    measurementId: 'G-BM1ZBL5NBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBooMZ5wmxopcZMtrtoQIVShdhT4fV16Ek',
    appId: '1:862488719088:android:b57595a1f8ac52ab449c35',
    messagingSenderId: '862488719088',
    projectId: 'genuine-app-20b4a',
    storageBucket: 'genuine-app-20b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSpD4k1-rle7HJuliHln3_EOCZRSq9sQ',
    appId: '1:862488719088:ios:c2571a19a33195d9449c35',
    messagingSenderId: '862488719088',
    projectId: 'genuine-app-20b4a',
    storageBucket: 'genuine-app-20b4a.appspot.com',
    iosClientId: '862488719088-gl2u67fhc97htkav788eisqaka254lk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.genuineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvSpD4k1-rle7HJuliHln3_EOCZRSq9sQ',
    appId: '1:862488719088:ios:c2571a19a33195d9449c35',
    messagingSenderId: '862488719088',
    projectId: 'genuine-app-20b4a',
    storageBucket: 'genuine-app-20b4a.appspot.com',
    iosClientId: '862488719088-gl2u67fhc97htkav788eisqaka254lk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.genuineApp',
  );
}
